### ISSUE TITLE
Delete short url record

### ISSUE THREAD

**Issue by mbos2** [mbos2/url-shortener#3]
**Is your feature request related to a problem? Please describe.**
There is no functionality to delete short URL record.

**Describe the solution you'd like**
Create an endpoint within the functionality for deleting shortUrl record.
Endpoint route: `/delete-record`
Endpoint method: `POST`
Endpoint payload: `{shortUrl}`

Additionally, add an option to delete a short record from the UI via button

Note: Try to follow code practices that are already present in the code

**Comment by GuyKh** [comment]
!assign

**Comment by GuyKh** [comment]
@mbos2 - You added the `hacktoberfest` tag, I just want to make sure - you actually participating in [Hacktoberfest](https://hacktoberfest.com/)?

**Comment by mbos2** [comment]
@GuyKh Yeah I'll be participating, but if you want I can assign you on this, I will make more issues. 
But I also got other repos I can contribute to :)

**Comment by mbos2** [comment]
@GuyKh I have assigned you to this issue. 

If you want to stop working on this at any point, please let me know so I can unassign.

**Comment by GuyKh** [comment]
👍🏻
